"""Add url column to images table

Revision ID: 0abf76e31045
Revises: 529319c56d2c
Create Date: 2024-11-09 22:09:48.129247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0abf76e31045'
down_revision = '529319c56d2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('style', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('mood', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('lighting', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('prompt',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('image_path')
        batch_op.drop_column('generated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('image_path', sa.VARCHAR(length=255), nullable=False))
        batch_op.alter_column('prompt',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('lighting')
        batch_op.drop_column('mood')
        batch_op.drop_column('style')
        batch_op.drop_column('url')

    # ### end Alembic commands ###
